### PR TITLE
Ubuntu + Blender 2.82.7

### PR DESCRIPTION
**Pull request by MoonMoon82**
Hi!

I get this error message if I try to activate Blender Molecular Script 1.1.1 or 1.1.0:

`Traceback (most recent call last):
  File "/home/christian/Dokumente/blender-2.82a-linux64/2.82/scripts/modules/addon_utils.py", line 382, in enable
    mod.register()
  File "/home/christian/.config/blender/2.82/scripts/addons/molecular/__init__.py", line 39, in register
    from . import operators
  File "/home/christian/.config/blender/2.82/scripts/addons/molecular/operators.py", line 18, in <module>
    from . import core_37_64 as core
ImportError: /home/christian/.config/blender/2.82/scripts/addons/molecular/core_37_64.cpython-37m-x86_64-linux-gnu.so: undefined symbol: __powf_finite

`

Is this a common issue in linux version of molecular script or did I do something wrong?

just in case you need the output of the console:
`PYTHON INTERACTIVE CONSOLE 3.7.4 (default, Oct  8 2019, 15:23:02)  [GCC 6.3.1 20170216 (Red Hat 6.3.1-3)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> import sys
>>> print(sys.version_info)
sys.version_info(major=3, minor=7, micro=4, releaselevel='final', serial=0)

>>> print(sys.version_info.major)
3
`

Kind regards

### CODE REVIEW

**Comment by PavelBlend** [comment]
I cannot fix this problem since I do not have a linux based system. Try installing version 1.1.1 from here:
https://github.com/scorpion81/Blender-Molecular-Script/releases/tag/1.1.1

If after reinstalling the error remains, then refer to @scorpion81 
Because he was engaged in assembly of the version for linux. Here is his fork:
https://github.com/scorpion81/Blender-Molecular-Script

**Comment by MoonMoon82** [comment]
@PavelBlend of course I (re)installed the versions (1.1.1 / 1.1.0)  of @scorpion81 . But it seems pull requests of you both are merged, so I can't open a new one on his fork.

@scorpion81 can you have a look at it please? I would be very glad if I can run molecular script under linux.

Thank you very much and kind regards,

**Comment by scorpion81** [comment]
@MoonMoon82 hmm, which version of ubuntu do you use ? I compiled the linux version under Linux Mint 19. Maybe that glibc version is too new or so... Hmm but since you are under linux as well, you should have a compiler at your disposal.
Basically you need to do `sudo apt install python3.7 python3.7-dev libpython3.7-dev` and then `python3.7 -m pip install Cython`. If there is an error saying there is no pip, `python3.7 -m ensurepip` should help.
If Cython is installed, you can git clone my molecular repo on github, and change to the directory where make_release.py is. Then just `python3.7 make_release.py` should spit out a ready to install zip including the python files and the built module. Lastly, install the new zip as addon in blender.

**Comment by MoonMoon82** [comment]
I'm using Ubuntu 20.04. 
Ubuntu 20.04 comes with python 3.8. And my attempts to build molecular script from your source code with python 3.8 failed.
But the issue regarding activating the addon in Blender should not be python 3.8 because molecular script uses the built-in python which is still 3.7 isn't it?

**Comment by scorpion81** [comment]
Ok, idk what the exact problem was with the previous build of mine... i Installed ubuntu 20.04 in a VM now, tried also with python 3.8 (couldnt import the resulting module) . Unfortunately there was no easy way to install python 3.7, so i checked out the blender sources and built the molecular module with the python included in there. Resulting file : (tested with 2.82a under Ubuntu 20.04)
[molecular_1.1.1_linux.zip](https://github.com/PavelBlend/Blender-Molecular-Script/files/4568486/molecular_1.1.1_linux.zip)

**Comment by MoonMoon82** [comment]
@scorpion81 Thank you very much! With this file no error messages appear anymore ! Great work, I really appreciate the effort you had!!

**Pull request closed without merging**
